name: Generate and publish Studienarbeit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: dokumentation.tex
          args: -pdf -synctex=1 -shell-escape -interaction=nonstopmode -output-directory=out/latex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Studienarbeit
          path: out/latex/dokumentation.pdf
